python code/predict_skeleton.py \
    --predict_data_list code/data/test_mixamo_at.txt \
    --data_root code/data \
    --model_name pct2 \
    --pretrained_model checkpoints/skeleton/AT_pose/mixamo/best_model_1425_mixamo.pkl \
    --predict_output_dir code/predict \
    --batch_size 16 \
    --num_sample 2048 \
    --vertices_sample 1024 \